---
title: "macrophage_analysis"
output:
  pdf_document: default
  html_document: default
---

```{r warning=FALSE, error=FALSE, message=FALSE, echo=FALSE, comment=NA}
knitr::opts_knit$set(global.par = TRUE)
```

```{r fig.width=22, fig.height=25, warning=FALSE, error=FALSE, message=FALSE, echo=FALSE, comment=NA}
#### load packages ####
library(plyr)
library(ggplot2)
library(RColorBrewer)
library(reshape2)
library(grid)
library(gridExtra)
```


```{r fig.width=22, fig.height=25, warning=FALSE, error=FALSE, message=FALSE, echo=FALSE, comment=NA}
#### set repository directory ####
## set baseDir if Knitting with RStudio button
baseDir <- "/Users/xuqiantan/Desktop/Su Lab/single_cell_macrophage/"

## sets path if run from runAnalysis.R
#currentFile <- rstudioapi::getActiveDocumentContext()$path
#baseDir <- gsub("single_cell_macrophage/.*", "single_cell_macrophage/", currentFile)

#### source function scripts ####
funcDir <- paste(baseDir, "src/functions/", sep="")
funcFiles <- c("loadData.R",
               "cleanCt.R",
               "clusterFilter.R",
               "violinPlot.R")
funcFiles <- paste(funcDir, funcFiles, sep="")
for(file in funcFiles){
  source(file)
}
```


```{r fig.width=22, fig.height=25, warning=FALSE, error=FALSE, message=FALSE, echo=FALSE, comment=NA}
## load data
ctTable <- loadData()
```


```{r fig.width=22, fig.height=25, warning=FALSE, error=FALSE, message=FALSE, echo=FALSE, comment=NA}
## norm all data
ctNorm <- cleanCt(ctTable, 
                  summaryOutput=T, 
                  cumExpCutoff=F, 
                  cumHist=F, 
                  normGene="none")
```


```{r fig.width=22, fig.height=25, warning=FALSE, error=FALSE, message=FALSE, echo=FALSE, comment=NA}
## cluster and filter
ctClust <- clusterFilter(ctNorm, 
                         testK = T, 
                         numCenters = 2, 
                         plotHeatmap=F, 
                         plotClustOnly=F,
                         heatmapFactor = "kmeans.cluster", 
                         heatmapColorBy = c("mouse"),
                         heatmapTissueLabel = "macrophage", 
                         fisherTests = c("mouse"),
                         cumulativeExpHist = T, 
                         filterClusters = F, 
                         clustersToRemove = NULL)


## recluster
# ctClust <- subset(ctClust, select = -kmeans.cluster)
# ctClust <- clusterFilter(ctClust, testK = T, numCenters = 8, plotHeatmap=T, plotClustOnly=F,
#                           heatmapFactor = "kmeans.cluster", heatmapColorBy = c("mouse", "probe", "age"),
#                           heatmapTissueLabel = "human samples", 
#                           fisherTests = c("mouse", "probe", "tissue", "age"),
#                           cumulativeExpHist = T, filterClusters = F, clustersToRemove = NULL)
```


```{r fig.width=22, fig.height=25, warning=FALSE, error=FALSE, message=FALSE, echo=FALSE, comment=NA}
#### violins ####
violinPlot(ctGenes=ctClust, 
           byFactor="kmeans.cluster", 
           factorOrder=c(1:2),
           groupLabel="clusters", 
           extraLabel="for macrophage samples",
           dotSize = 1.5, 
           dotAlpha = 0.3)

violinPlot(ctGenes=ctClust, 
           byFactor="mouse", 
           factorOrder=c(1, 4:9),
           groupLabel="mice", 
           extraLabel="for macrophage samples",
           dotSize = 1.5, 
           dotAlpha = 0.3)

#### bottom ####
```
